keras-team/keras-rs

examples/basic_ranking.py
examples/basic_retrieval.py

Example was run with all 3 backends (tf, jax and torch).

Add basic ranking example.

---

keras_rs/src/layers/retrieval/brute_force_retrieval.py

For consistency with other layers. Note that this does not serialize candidates.

Add `get_config` to `BruteForceRetrieval` layer.

---

keras_rs/src/api_export.py

The `keras_rs_export` decorator was not calling `register_keras_serializable` correctly.

Fix Keras RS object serialization.

---

keras_rs/src/layers/retrieval/brute_force_retrieval.py

For consistency, we use the lower case versino when available.

Use `tuple` instead of `Tuple` in type annotation.

---

keras_rs/src/layers/modeling/dot_interaction.py
keras_rs/src/layers/modeling/dot_interaction_test.py
keras_rs/src/utils/keras_utils.py

- Using `tril_mask` to pick the lower triangular part of the matrix does not work for JAX when `skip_gather` is `False`. So, we generate indices and then index into the array.
- Cannot compare shapes directly.

Fix dot interaction

---

examples/basic_ranking.py
examples/basic_retrieval.py
examples/data_parallel_retrieval.py
examples/deep_recommender.py
examples/scann.py
examples/sequential_retrieval.py

In this example, we add features for both movies and user, and compare networks of different depths for both towers.

Add deep recommender example.

---

keras_rs/api/layers/__init__.py
keras_rs/src/layers/modeling/dot_interaction.py
keras_rs/src/layers/modeling/dot_interaction_test.py
keras_rs/src/layers/modeling/feature_cross.py
keras_rs/src/layers/modeling/feature_cross_test.py
keras_rs/src/layers/retrieval/hard_negative_mining.py
keras_rs/src/layers/retrieval/hard_negative_mining_test.py

This layer extract negative logits and labels.

Add Hard Negative Mining Layer.

---

keras_rs/src/layers/retrieval/hard_negative_mining.py
keras_rs/src/layers/retrieval/remove_accidental_hits.py
pyproject.toml
requirements-common.txt

This is consistent with Keras' usage of `ml_dtypes`.
Also added `ml_dtypes` as a pip package dependency.

Use `ml_dtypes` instead of `numpy` for `finfo`.

---

keras_rs/src/layers/retrieval/remove_accidental_hits.py
keras_rs/src/layers/retrieval/remove_accidental_hits_test.py

The order is now `logits`, `labels`, which is more consistent with the other layers and Keras in general.

Change order of call args in `RemoveAccidentalHits` layer.

---

keras_rs/src/testing/test_case.py

`keras.utils.clear_session()` actually clears that flag.

Fix disabling of traceback filtering in unit test.

---

keras_rs/src/utils/pairwise_loss_utils.py

Fix invalid type annotation.

---

keras_rs/api/layers/__init__.py
keras_rs/src/layers/retrieval/brute_force_retrieval.py
keras_rs/src/layers/retrieval/retrieval.py
keras_rs/src/layers/retrieval/retrieval_test.py

Question for you, @hertschuh:
- I have kept doc-strings from `BruteForceRetrieval`'s `call()`, `update_candidates()`, etc., and kept them in the abstract class as well. This leads to duplication, but also ensures complete API documentation on keras.io. Let me know if you want to remove it in one of the classes.
- Is `BaseRetrieval` a better name?

Add base retrieval class

---

keras_rs/src/layers/retrieval/hard_negative_mining.py
keras_rs/src/layers/retrieval/hard_negative_mining_test.py

Also simplified the code by using an existing keras op.
Added unit test to cover the case when the inputs have fewer candidates than the requested number of hard negatives.
Fixes https://github.com/keras-team/keras-rs/issues/39

Add support for any dimensions to `HardNegativeMining` layer.

---

keras_rs/src/layers/retrieval/sampling_probability_correction_test.py

The `SamplingProbabilityCorrection` already supports different dimensions. This adds testing for it.
See https://github.com/keras-team/keras-rs/issues/39

Test `SamplingProbabilityCorrection` layer with different dimensions.

---

requirements-jax-cuda.txt
requirements-tensorflow-cuda.txt
requirements-torch-cuda.txt
requirements.txt

They are not needed and were removed from the Keras requirements files.

Remove `torchvision` from requirements files.

---

keras_rs/src/metrics/mean_average_precision.py
keras_rs/src/metrics/mean_reciprocal_rank.py
keras_rs/src/metrics/precision_at_k.py
keras_rs/src/metrics/ranking_metric.py
keras_rs/src/metrics/ranking_metrics_utils.py
keras_rs/src/metrics/recall_at_k.py

I know we'd discussed that we can probably do
```
keras.backend.result_dtype(y_true.dtype, y_pred.dtype)
```
but looks like this is the correct way to do it? Just use `self.dtype`

Cast tensors to the correct dtype for metrics

---

keras_rs/src/version.py

The version on main should be a dev version, because sometimes, people accidentally cut a release on `main`, which results in a release. If we set the version to a dev version, it'll just be a pre-release even by accident.
(this is how we do it on KerasHub too)

Change main version to 0.1.1.dev0

---

requirements-jax-cuda.txt

Will be required for the distributed embedding layer on JAX.

Add jax-tpu-embedding dependency for large embeddings.

---

keras_rs/src/layers/embedding/embed_reduce.py
requirements-common.txt
requirements.txt

Unfortunately `keras.ops.ones_like` discards the sparsity pattern for sparse tensors, instead filling a dense tensor with the same overall shape.
There don't seem to be any standard utilities in Keras for manipulating sparse tensors across multiple backends.  All math functions that operate on sparse tensors intentionally treat explicit `0`s the same as implicit zeros, preventing us from using math tricks to get a sparse tensor of ones.  So, we resort to adding backend-specific checks here.
Currently only TF and JAX are supported.

Fix embed_reduce for sparse inputs.

---

keras_rs/src/layers/embedding/base_distributed_embedding.py
keras_rs/src/layers/embedding/distributed_embedding_config.py
keras_rs/src/layers/embedding/embed_reduce.py

Specific TF and JAX documentation will be added with support.
Also:
- fixed `EmbedReduce` doc rendering
- simplified `TableConfig` default initializer by removing parameter that is the default

Add backend/hardware-independent doc for `DistributedEmbedding`.

---

keras_rs/src/layers/embedding/base_distributed_embedding.py
keras_rs/src/layers/embedding/distributed_embedding_test.py
keras_rs/src/layers/embedding/jax/config_conversion.py
keras_rs/src/layers/embedding/jax/distributed_embedding.py
keras_rs/src/layers/embedding/jax/distributed_embedding_test.py
keras_rs/src/layers/embedding/jax/embedding_lookup.py
keras_rs/src/layers/embedding/jax/embedding_lookup_test.py
keras_rs/src/layers/embedding/jax/embedding_utils.py
keras_rs/src/layers/embedding/jax/test_utils.py
pyproject.toml

Also updated some minor issues encountered in testing on sparsecores.

Move preprocess to base distributed embedding class.

---

keras_rs/src/layers/embedding/jax/distributed_embedding.py
keras_rs/src/layers/embedding/jax/embedding_lookup.py

The function does still exist in `jax.experimental.shard_map`, but is an alias in the latest JAX version.  Since we support older JAX versions (i.e. 0.6.0), we need to keep the original reference.

Ignore shard_map attr error in mypy.

---

keras_rs/src/layers/embedding/embed_reduce.py
keras_rs/src/layers/embedding/embed_reduce_test.py

`EmbedReduce` was inheriting the behavior from `Embedding` and not correctly applying the reduction.

Fix symbolic calls for `EmbedReduce`.

---

keras_rs/src/layers/embedding/jax/embedding_lookup_test.py
keras_rs/src/layers/embedding/jax/test_utils.py

Keras can already depend on either `dmtree` or `optree` and use whichever is best or available on the current platform.

Remove dependency on `tree` and use `keras.tree`.

---

keras_rs/src/layers/embedding/distributed_embedding.py
requirements-jax-cuda.txt
requirements.txt

This is the simplest approach to avoiding importing jax-tpu-embedding on non-supported platforms.
Note that the jax/ subfolder will still cause issues with api_gen though, and anyone trying to explicitly run `pytest` on the `jax/` subfolder.

Only enable JAX on linux_x86_64.

---

keras_rs/src/layers/embedding/jax/config_conversion.py

This is for forward-compatibility.  Latest versions of JAX introduce the `out_sharding` argument.

Add out_sharding argument WrappedKerasInitializer.

---

keras_rs/src/layers/embedding/base_distributed_embedding.py
keras_rs/src/layers/embedding/distributed_embedding_config.py
keras_rs/src/layers/embedding/embed_reduce.py
keras_rs/src/layers/embedding/jax/config_conversion.py
keras_rs/src/layers/embedding/jax/config_conversion_test.py
keras_rs/src/layers/embedding/jax/distributed_embedding.py
keras_rs/src/layers/embedding/jax/distributed_embedding_test.py
keras_rs/src/layers/embedding/jax/embedding_lookup.py
keras_rs/src/layers/embedding/jax/embedding_lookup_test.py
keras_rs/src/layers/embedding/jax/embedding_utils.py
keras_rs/src/layers/embedding/jax/test_utils.py
keras_rs/src/layers/embedding/tensorflow/config_conversion.py
keras_rs/src/layers/embedding/tensorflow/distributed_embedding.py
keras_rs/src/layers/embedding/test_utils.py
keras_rs/src/layers/feature_interaction/feature_cross.py
keras_rs/src/layers/retrieval/brute_force_retrieval.py
keras_rs/src/layers/retrieval/retrieval.py
keras_rs/src/losses/pairwise_loss.py
keras_rs/src/losses/pairwise_mean_squared_error.py
keras_rs/src/metrics/dcg.py
keras_rs/src/metrics/ndcg.py
keras_rs/src/metrics/ranking_metric.py
keras_rs/src/metrics/ranking_metrics_utils.py
keras_rs/src/metrics/utils.py
keras_rs/src/types.py
pyproject.toml

Now that we require Python 3.10, we can use the shorter annotation style, which should improve the readability of the documentation.

Use Python 3.10 style type annotations.

---

pip_build.py

Tested by inspecting `python3.10/site-packages/keras_rs` before and after.

Do not bundle test utils in wheel.

---

keras_rs/src/layers/embedding/jax/embedding_lookup_test.py

This instance was missed as it is only run on TPU.

Replace leftover `unflatten_as` to `pack_sequence_as`.

---

keras_rs/src/layers/embedding/base_distributed_embedding.py
keras_rs/src/layers/embedding/distributed_embedding_test.py
keras_rs/src/layers/embedding/jax/distributed_embedding_test.py
keras_rs/src/layers/embedding/test_utils.py

Requires calling `preprocess`.
Internally, we currently convert ragged inputs to dense before passing to the embedding call(...) function.

Add ragged support for default_device placement on JAX.

---

keras_rs/src/layers/embedding/base_distributed_embedding.py
keras_rs/src/layers/embedding/distributed_embedding.py
keras_rs/src/layers/embedding/jax/distributed_embedding.py

This is to allow users to potentially run Keras RS _without_ the dependency.
If a user doesn't have `jax-tpu-embedding` installed, but are on `linux_x86_64` and has a sparsecore-capable TPU available, and if they try to use `auto` or `sparsecore` placement with distributed embedding, will raise an error informing them to install the dependency.

Check for jax_tpu_embedding on JAX backend.

---

keras_rs/src/layers/embedding/base_distributed_embedding.py

The JAX usage section was broken.

Fix docstring for `DistributedEmbedding`.

---

keras_rs/src/layers/embedding/base_distributed_embedding.py

The first code block was missing syntax highlighting.

Minor docstring fix in `DistributedEmbedding`.

---

pip_build.py

Nightly builds no longer worked because of the addition of a suffix of `.dev0` in the `version.py` file.
The fix is the same as on [`keras-hub`](https://github.com/keras-team/keras-hub/blob/master/pip_build.py#L51).

Fix nightly builds.

---

keras_rs/src/layers/embedding/jax/distributed_embedding.py
keras_rs/src/layers/embedding/jax/distributed_embedding_test.py
keras_rs/src/layers/embedding/jax/embedding_lookup.py
requirements-jax-cuda.txt

This reflects an upstream change in JAX.

Update references of jax_layout.Layout to jax_layout.Format.

---

keras_rs/src/layers/embedding/jax/distributed_embedding.py
keras_rs/src/layers/embedding/jax/distributed_embedding_test.py

`DeviceLocalLayout` is becoming `Layout`.

Change for `DeviceLocalLayout` in JAX 0.6.3.

---

keras_rs/src/layers/embedding/jax/distributed_embedding.py
keras_rs/src/layers/embedding/jax/distributed_embedding_test.py

Type verification fails after removal.

Fix for removal of JAX `DeviceLocalLayout`.

---

keras_rs/src/layers/embedding/jax/distributed_embedding.py
keras_rs/src/layers/embedding/jax/distributed_embedding_test.py

The `jax.experimental.layout.Layout` argument is renamed from `_tiling` to `tiling`.

Fix JAX Layout tiling argument for JAX 0.7.1

---

keras_rs/src/layers/embedding/distributed_embedding_test.py

Fixed inconsistencies between the per TPU batch size and global batch size.

Fix batch sizes in `distributed_embedding_test.py`.

---

.github/workflows/actions.yml
.github/workflows/nightly.yml
.github/workflows/publish-to-pypi.yml
pyproject.toml
requirements-jax-cuda.txt
requirements-tensorflow-cuda.txt
requirements-torch-cuda.txt
requirements.txt

- `jax-tpu-embedding` now requires `jax>=0.7.0`.
- `jax>=0.7.0` requires Python 3.11
- `jax-tpu-embedding` also requires a more recent version of `protobuf` than what comes with Tensorflow 2.18 and 2.19, requiring an upgrade to 2.20.

Bump Python, JAX and Tensorflow versions

---

keras_rs/src/layers/embedding/distributed_embedding_test.py
keras_rs/src/layers/embedding/tensorflow/distributed_embedding.py

The number of SparseCore chips per TPU is now retrieved from the strategy. This makes the `distributed_embedding_tests.py` pass on V6e.

DistributedEmbedding: do not hardcode the number of SparseCores with TF.

---

keras_rs/src/layers/embedding/jax/embedding_lookup_test.py
keras_rs/src/layers/embedding/jax/test_utils.py

This change updates the Keras-RS JAX embedding tests to use the `embedding.EmbeddingVariables` dataclass from `jax_tpu_embedding` for representing embedding tables and slot variables, instead of a custom tuple structure. This involves updating type hints, variable access, and build dependencies.

Refactor: Use `embedding.EmbeddingVariables` in Keras-RS JAX embedding tests.
